---

# List of public keys
ssh_keys: [ ]

# VPC settings
vpc:
  description: Homebox VPC
  subnet: 172.16.10.0/24
  region: ams

# Virtual machine settings
vm:
  plan: vc2-1c-2gb
  region: ams
  os: Debian 12 x64 (bookworm)

firewall:
  name: Homebox firewall
  rules:
    ingress:
      - comment: Accept SSH connections
        port: 22
        protocol: tcp
        version: v4, v6
      - comment: Accept DNS queries on UDP
        port: 53
        protocol: udp
        version: v4, v6
      - comment: Accept DNS queries on TCP
        port: 53
        protocol: tcp
        version: v4, v6
      - comment: Accept http traffic
        port: 80
        protocol: tcp
        version: v4, v6
      - comment: Accept https traffic
        port: 443
        protocol: tcp
        version: v4, v6
      - comment: Accept email SMTP traffic
        port: 25
        protocol: tcp
        version: v4, v6
      - comment: Accept email IMAPS traffic
        port: 993
        protocol: tcp
        version: v4, v6
      - comment: Accept email POP3S traffic
        port: 995
        protocol: tcp
        version: v4, v6
      - comment: Accept email Submission traffic
        port: 587
        protocol: tcp
        version: v4, v6
      - comment: Accept email SMTPS traffic
        port: 465
        protocol: tcp
        version: v4, v6
      - comment: Accept Jabber c2s encrypted traffic
        port: 5223
        protocol: tcp
        version: v4, v6
      - comment: Accept Jabber s2s encrypted traffic
        port: 5269
        protocol: tcp
        version: v4, v6
